### ISSUE TITLE
merge Forks

### ISSUE THREAD

**Issue by asecondwill** [symbiote-library/silverstripe-link-mapping#10]
There are some forks that have really taken this on, it might be worth marking this repo as abandoned? Ideally there would be issue tracking & an entry in SS addons  / composer support for the latest version of the module working with the latest SS. 

W

**Comment by nglasl** [comment]
This module has been superceded by the misdirection module, and is therefore no longer maintained.

https://github.com/nglasl/silverstripe-misdirection
